### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by 1221328** [IlyaKrotov/BitMEX-simple-trading-robot#1]
Strategy.py 
Traceback (most recent call last):
  File "C:\Users\PB\Desktop\BitMEX-simple-trading-robot-master\strategy.py", line 1, in <module>
    import talib
ImportError: No module named talib

Current directory:
C:\Users\PB

Command to be executed:
"C:\WINDOWS\system32\cmd.exe" /C "C:\Users\PB\Desktop\BitMEX-simple-trading-robot-master\strategy.py"

--------------------------------------------------
Trader.py
  File "C:\Users\PB\Desktop\BitMEX-simple-trading-robot-master\trader.py", line 12
    print(f"Last prediction: {prediction}")
                                         ^
SyntaxError: invalid syntax

Current directory:
C:\Users\PB

Command to be executed:
"C:\WINDOWS\system32\cmd.exe" /C "C:\Users\PB\Desktop\BitMEX-simple-trading-robot-master\trader.py"

---------------------------------------------------
Main_loop.py
Traceback (most recent call last):
  File "C:\Users\PB\Desktop\BitMEX-simple-trading-robot-master\main_loop.py", line 1, in <module>
    import bitmex
ImportError: No module named bitmex

Current directory:
C:\Users\PB

Command to be executed:
"C:\WINDOWS\system32\cmd.exe" /C "C:\Users\PB\Desktop\BitMEX-simple-trading-robot-master\main_loop.py"

**Comment by IlyaKrotov** [comment]
You have to install the following libs:
1. talib (https://github.com/mrjbq7/ta-lib)
2. bitmex (https://github.com/BitMEX/api-connectors/tree/master/official-http/python-swaggerpy)

And finally, your python must be at least 3.6 version for using f-strings (ex: f"Last prediction: {prediction}")

Then you can successfully run the code.

**Comment by 1221328** [comment]
I have still got a problem with talib. I have ran a command - pip install TA-lib but it still says that it is not there.

**Comment by 1221328** [comment]
I got this problem 
    ----------------------------------------
Command "c:\users\administrator\appdata\local\programs\python\python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\3\\pip-install-_8hutpuv\\TA-Lib\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\ADMINI~1\AppData\Local\Temp\3\pip-record-z8hc4ocx\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\ADMINI~1\AppData\Local\Temp\3\pip-install-_8hutpuv\TA-Lib\

**Comment by 1221328** [comment]
I am very frustrated, what should I do to make the bot work?

**Comment by hashtagex** [comment]
I think but may be wrong on windows you have to do something to get TA-lib
to work if you can?  Google Search should find something.

**Comment by IlyaKrotov** [comment]
I wrote this code on Mac OS X. Seems that your problem mostly about ta-lib. So try to google how to install it correctly on Windows. It may help https://stackoverflow.com/questions/45337509/failing-on-install-talib-in-windows-7

**Comment by Aig21** [comment]
got some problems initially, but after installations of pandas, ta-lib, numpy all works fine

**Comment by hashtagex** [comment]
Are you using conda for this? Because I am getting this error:
RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)

**Comment by ghost** [comment]
I fixed it.

**Comment by IlyaKrotov** [comment]
I wrote the code in Jupyter notebook without using conda, just pip.

**Comment by hashtagex** [comment]
Got it working thanks a lot.
